"""Build-time feature flags (regenerated by scripts/generate_build_meta.py before packaging)."""

from __future__ import annotations

BUILD_FLAVOR: str = "memory"
BUILD_VERSION: str = "1.4.3"
AUTO_KICK_ENABLED: bool = True
MEMORY_SCAN_AVAILABLE: bool = True
APP_EXE_BASENAME: str = "AntiSmurf"
APP_DISPLAY_NAME: str = "AntiSmurf"
INSTALLER_BASENAME: str = "AntiSmurf-Setup"
