"""Build-time feature flags (regenerated by scripts/generate_build_meta.py before packaging)."""

from __future__ import annotations

BUILD_FLAVOR: str = "memory"
BUILD_VERSION: str = "1.3.0"
AUTO_KICK_ENABLED: bool = True
MEMORY_SCAN_AVAILABLE: bool = True
APP_EXE_BASENAME: str = "AntiSmurf-Memory"
APP_DISPLAY_NAME: str = "AntiSmurf (内存扫描)"
INSTALLER_BASENAME: str = "AntiSmurf-Memory-Setup"
