#!/usr/bin/env python3
"""Write src/antismurf/build_meta.py for memory-scan release builds."""

from __future__ import annotations

import argparse
from pathlib import Path

TEMPLATE = '''"""Build-time feature flags (regenerated by scripts/generate_build_meta.py before packaging)."""

from __future__ import annotations

BUILD_FLAVOR: str = "memory"
BUILD_VERSION: str = "{version}"
AUTO_KICK_ENABLED: bool = {auto_kick_enabled}
MEMORY_SCAN_AVAILABLE: bool = True
APP_EXE_BASENAME: str = "AntiSmurf"
APP_DISPLAY_NAME: str = "AntiSmurf"
INSTALLER_BASENAME: str = "AntiSmurf-Setup"
'''


def _read_version(root: Path) -> str:
    version_file = root / "VERSION"
    if version_file.exists():
        return version_file.read_text(encoding="utf-8").strip()
    return "dev"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate antismurf build_meta.py")
    parser.add_argument(
        "--gray",
        action="store_true",
        help="灰度发布：关闭自动踢人，BUILD_VERSION 追加 -gray",
    )
    parser.add_argument(
        "--enable-auto-kick",
        action="store_true",
        help="打包时启用自动踢人",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    target = root / "src" / "antismurf" / "build_meta.py"
    version = _read_version(root)
    if args.gray and "-gray" not in version:
        version = f"{version}-gray"
    auto_kick = "True" if args.enable_auto_kick and not args.gray else "False"
    target.write_text(
        TEMPLATE.format(version=version, auto_kick_enabled=auto_kick),
        encoding="utf-8",
    )
    print(
        f"Wrote {target} (version={version}, auto_kick={auto_kick})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
